# Generated by Django 2.1.2 on 2018-10-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete='DO NOTHING', related_name='user_joining_wishes', to='wish_list_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('date_added', models.DateTimeField()),
                ('added_by', models.ForeignKey(on_delete='DO NOTHING', related_name='items', to='wish_list_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='join',
            name='wish',
            field=models.ForeignKey(on_delete='DO NOTHING', related_name='wishes_joined_by_users', to='wish_list_app.Wish'),
        ),
    ]
