# Generated by Django 2.1.2 on 2018-10-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list_app', '0002_auto_20181023_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='desc',
        ),
    ]
