# Generated by Django 2.1.2 on 2018-10-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wish_list_app', '0006_auto_20181023_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='added_by_user',
            field=models.CharField(default='thomas', max_length=255),
            preserve_default=False,
        ),
    ]
